# TODO: Fix everything in here:
inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - "*/examples/**/*"  # For now, don't lint the examples
    - "vendor/**/*"
  TargetRubyVersion: 2.3

Layout/DotPosition:
  EnforcedStyle: trailing

Metrics/BlockLength:
  ExcludedMethods: ["describe", "context"]

Metrics/MethodLength:
  Max: 12

Style/Documentation:
  Exclude:
    - "*/spec/**/*"

Style/FrozenStringLiteralComment:
  Exclude:
    - "Gemfile"
    - "Rakefile"
    - "flow.gemspec"
    - "**/*.gemspec"
    - "*/spec/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  MinSize: 3
